name:                servant-photo-gallery
version:             0.1.0.0
github:              "rogryza/servant-photo-gallery"
license:             MIT
author:              "Rodrigo Gryzinski"
maintainer:          "rogryza@gmail.com"
copyright:           "2019 Rodrigo Gryzinski"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Photo gallery API server
category:            Program

description:         Please see the README on GitHub at <https://github.com/githubrogryza/servant-photo-gallery#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - LambdaCase
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators

library:
  source-dirs: src
  dependencies:
    - JuicyPixels
    - aeson
    - bytestring
    - cryptonite
    - directory
    - filepath
    - htoml
    - http-api-data
    - http-media
    - http-types
    - jose
    - lens
    - monad-logger
    - mtl
    - network-uri
    - servant
    - servant-auth
    - servant-auth-server
    - servant-multipart
    - servant-server
    - sqlite-simple
    - text
    - time
    - unordered-containers
    - uuid
    - wai
    - wai-cors
    - warp
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

executables:
  servant-photo-gallery-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-photo-gallery

tests:
  servant-photo-gallery-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - containers
    - directory
    - hedgehog
    - hedgehog-corpus
    - mmorph
    - mtl
    - network-uri
    - servant-photo-gallery
    - unordered-containers
