name: Haskell CI
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: cache stack
      uses: actions/cache@v1
      with:
        path: /home/runner/.stack
        key: build-cache-stack
    - name: cache stack-work
      uses: actions/cache@v1
      with:
        path: .stack-work
        key: build-cache-stack-work-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          build-cache-stack-work
    - name: Stack setup
      run: stack setup
    - name: Intsall CI tools
      run: stack install brittany hlint weeder
    - name: Build dependencies
      run: stack build --dependencies-only --fast
    - name: Build project
      run: stack build --fast
    - name: Run linters
      env:
        PATH: $PATH:$(stack path --local-bin)
      run: scripts/lint.py
    - name: Run tests
      run: stack test --fast
