name: Haskell CI
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v6
    - name: Lint
      run: nix-shell --packages python3 --run 'scripts/lint.py'
    - name: Test
      run: nix-shell -- run 'stack test --fast'
