name: Haskell CI
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: cache stack
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: /home/runner/.stack
        key: build-${{ env.cache-name }}
        restore-keys: |
          build-${{ env.cache-name }}
          build-
    - name: cache stack-work
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-work
      with:
        path: .stack-work
        key: build-${{ env.cache-name }}-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          build-${{ env.cache-name }}
          build-
    - name: Stack setup
      run: stack setup
    - name: Intsall CI tools
      run: stack install brittany hlint weeder
    - name: Build dependencies
      run: stack build --dependencies-only --fast
    - name: Build project
      run: stack build --fast
    - name: Run linters
      run: scripts/lint.py
    - name: Run tests
      run: stack test --fast
